<section>
    <h1><?= $judul; ?></h1>
    <p align='justify'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa sapiente ipsam aperiam dignissimos impedit vero nihil exercitationem porro quidem est? Possimus voluptatum enim hic veniam amet veritatis impedit animi nemo?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero quod voluptate quos sunt deserunt reprehenderit fugiat aut, consequatur modi corporis quia velit ipsam eaque accusamus voluptates, alias a laboriosam dolorem!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta non possimus odit molestiae officiis doloribus officia quas dolorum doloremque voluptas unde porro repellat dolor qui rem, minima illum voluptates pariatur?</p>
    <ol type="a">
        <li>Model</li>
        <p align="justify">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam vel ratione tempora, voluptates omnis culpa necessitatibus similique laboriosam possimus nostrum iste natus vitae corrupti! Magnam sunt totam vero ipsa autem. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur rem dolores tempora repellat. Sit ullam nemo explicabo! Eaque magnam maxime vero facilis veniam eos repudiandae, odio, exercitationem inventore libero quisquam. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quam labore officiis maxime molestiae blanditiis vel, qui reprehenderit placeat in enim illum. Optio accusamus vel, ipsa sequi maiores dolores itaque! Molestias?</p>
        <li>View</li>
        <p align="justify">Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus harum, praesentium cum maxime labore ipsam amet, magnam quasi qui dolor exercitationem est doloremque reprehenderit, nobis illo quos corporis placeat ea!Loremlorem Lorem ipsum dolor sit, amet consectetur adipisicing elit. Amet sint quas cum ab consequatur debitis et aut doloribus praesentium. Placeat odio veritatis beatae tempora quia natus suscipit. Voluptate, deleniti iusto?Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur explicabo sint aut reprehenderit inventore perspiciatis adipisci officia voluptatum tenetur sit cumque rem natus exercitationem doloribus unde laudantium, saepe nam incidunt.</p>
        <li>Controller</li>
        <p align="justify">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laboriosam perferendis minima sunt dolore, aspernatur iure cum impedit, nihil quibusdam fugiat saepe dolores beatae, perspiciatis quidem reprehenderit at vitae! Iste, nemo?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Totam, saepe? Eum iure magnam tempora recusandae debitis nulla deserunt quisquam, quidem cum tempore dolore, excepturi iste odio, laborum nemo voluptatibus error?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus distinctio quaerat similique, qui ratione enim accusantium perspiciatis deleniti, corporis excepturi reiciendis doloremque magnam amet dolores unde ducimus explicabo voluptatem assumenda.</p>

    </ol>
</section>